#!/usr/bin/python3
import snakeoil3_gym as snakeoil 
if __name__ == "__main__":                     
    C= snakeoil.Client(p=3101)                       
    for step in range(C.maxSteps,0,-1):      
        print( C.get_servers_input() )
        snakeoil.drive_example(C)              
        C.respond_to_server()                  
    C.shutdown()                               
